# Information
site_name: 原点效应
site_url: https://zh.origineffect.net
site_description: 原点效应文档

# Configuration
theme:
  name: material
  language: zh
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon:  octicons/sun-16
        name: 切换至深色模式
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: octicons/moon-16
        name: 切换至浅色模式
  features:
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes

# Hooks
hooks:
  - overrides/hooks/i18n-stayonpage.py

# Additional
extra:
  alternate:
    - name: 简体中文
      link: https://zh.origineffect.net
      lang: zh
    - name: English
      link: https://origineffect.net
      lang: en

# Navigation
nav:
  - 首页: index.md
  - 立方内核: cube-core/index.md