# Information
site_name: 原点效应
site_url: https://zh.origineffect.net
site_description: 原点效应文档

# Configuration
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换至浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: 切换至系统偏好
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes

# Additional
extra:
  alternate:
    - name: 简体中文
      link: zh.origineffect.net
      lang: zh
    - name: English
      link: origineffect.net
      lang: en

# Navigation
nav:
  - 首页: index.md
  - 立方内核: cubecore/index.md